# .streamlit/secrets.toml
# 這是你管理員頁面的密碼，請自己設定
admin_password = "adminadmin"

# 以下是從 Google JSON 憑證檔案中複製過來的內容
[gcp_service_account]
type = "service_account"
project_id = "level-ward-427808-j9"
private_key_id = "07f0678752367de8f7783dfbae19489712323d56"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCj6C4IAwHK6elq
32quRPeTIEaEaRTTbH6sqwoJQC4teQlM9clWE9RPanMr/iZogl0HYngNUKSHSoSJ
1JkHC/v6xXLFNnCCmMVqJCvuAsGtFB9rDQY953cU2HOMUmgG0zOwzeL1gDrFIXjg
vOygmkoCRVt5PFsKiFFEe0Ivy0ux8LDl/KFB1GlRObq0bCa3JCnOB3p1/dLjsff/
wvXDI20WaFHXkQupHAHel/awo+EA7r+sijYmWyo9byKjjix5MpTAn1aF6R84Mkz3
2VwdwRFY0sJU+/uwSYlpILb6+JdsUE4C0fb88CE22CAo0fiuo/gcimHP4Z7k2p1R
dbqBxDkPAgMBAAECggEATCzJx9tt59oSKyMuN1PCI9RqMXuMvD2+GY1cGrSDQYrw
8Z2BNsn8b/QvFpEFVKjRh28SEE4cSOwu8MenXwkI0KEXF+SXIXrStOOerv0E+eVS
PLRO5FJAm6WE/gAGbLWXXmIxSpuPtLI7tWbYKkPKhYeqXYvZW+nCqysFtaSrx0Qw
ffPBrE5t0GjswcmAswv91Y5Itwlw92YvYHK8kXRUu5bINFdSZ5wsbfQWSIXuxrwh
U3M/SbZ+3cWNKicADz5ElteOWyaAN72aboCyvVTigdCu2LnhVWKZBjzNphBcPrlO
ScSR3wc8X1GOmhlM9T6poAJiVKpuQjTJVP0yO0D3YQKBgQDbEIhmrDiAjT3A8910
L4jyegZjdvRiALx4aPMGu8jiMpSQ8dwDe8Z6sg5ivDju8Y0CoweJqF7SfHCn4pU6
UY10ZVssAUBIDA6+437ud1GLPdLHaiMZTAnp5TTroYdCuerxIuZo+X+Ta3mUy1Of
6keMV4JKAiEmu2U/4boVG9ocqQKBgQC/iuHzejmAljRQIglfd3rMia19wv144Y3X
WVZFXQsuSL3rRBUpiYP0/ivGphB61nSU+3xuWqtuZQ51Phrd5Y/hQlX1NShd4tCl
fre2rDRjM7NfCvtceOROvHAXGtveyDxnsPq0IAqBVWFaMuGEXiAmUl7L2N+pOZ70
9sfFzddC9wKBgEJZzZabjzmQjiXFN0wbobUftJOn0fllE7C8yO8/LWclvs3wE52S
fdln2Oea7vugef9UddICB0ZlnpGbFWvmi5u3n1fCwT+RN14l9aowxagQ/6iawyrE
VzRa0h6UfC1/tmN3GKau+y8hnF+u/hMvmKAvWS0lW/kpRU+GBSCjoPqRAoGAf7Jr
qRMXOu7ouXO3o/nX2H0BORLCQdC965AXv+6kAZtlYm/lW+feHXtGXA1id0J6Psja
0AeKuvKMjQV2i/D710WOYQerfcw1JeAxQovT8T8KmpaLtb6zFvryD7VMWF5ORyLq
QSQLXOY7HRNG3iSScnn/0Q8pLXzIyK+tx+XPWUkCgYAbuixB0SNMoDjG6lgLIaII
jANYhdVdeIyVTIljvg6fb1w+HsjCu3EM85/Rzwz2m42nLpVnavTs6f25ysE2Zndv
4AaAPu6cg5RJuoD7+kePspT8P/KNej/Id1EHHKFK+pr/kizwl+ehi6VAdRGohOCM
h9TCv3jiMDraLvXxHYjGmA==
-----END PRIVATE KEY-----"""
client_email = "streamlit-lottery-service@level-ward-427808-j9.iam.gserviceaccount.com"
client_id = "115459754369546737753"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-lottery-service%40level-ward-427808-j9.iam.gserviceaccount.com"
universe_domain = "googleapis.com"